name: Terraform Format, Validate, and Test

permissions:
  contents: read
  # Adicione permissões extras apenas se necessário

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: 1.9.3

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Format
      run: terraform fmt -check -recursive -diff

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Test
      run: terraform test
